### ISSUE TITLE
Phenology

### ISSUE THREAD

**Issue by acvaughan** [hiscom/hispid#12]
The HISPID vocabulary for phenology is much smaller than what is implemented in some herbaria (or what some herbaria would like to implement), and the the vocabulary needs to be expanded to better describe non-flowering plants. (From the minutes of the 2012 HISCOM meeting: http://hiscom.rbg.vic.gov.au/wiki/HISCOM_2012_AGM_Canberra_minutes#11._HISPID.)

**Comment by nielsklazenga** [comment]
See http://hiscom.rbg.vic.gov.au/wiki/HISPID_3#Phenology_.28phe.29 for the HISPID 3 definition and vocabulary. The list of terms is a bit pathetic for cryptogams, but I doubt a better list would get much use, as these plants are not called cryptogams for nothing.

'gametophyte' and 'sporophyte' are not reproductive structures or phenological states, they are generations. The correct terms to replace them would be 'gametophore' and 'sporogone' (at least in bryophytes; don't know about ferns and the like (they won't have a gametophore)).

There are many terms available for cryptogams that would be useful to have in a reproductiveCondition field if the information were available, such as 'mature capsules' and the different stages of archegonial and antheridial development. But it would have to be a rather fine-grained list. I only know a little about this, but Pina did her PhD on it.

As a taxonomist I used to score whether a collection had sporogones or not (not in MELISR, as we don't have a field for it), as they are rare in the groups I have worked with and they don't have characters I would expect to be diagnostic within the groups, so I would ignore them in my taxonomic studies. However, when it became time to write the description, it was very handy to know which specimens have capsules (and not just capsules, but also peristomes that are in a good enough condition to study and calyptrae etc.). Just saying this, because before the mosses, when I was working on African begonias, I would use the same thing with flowers and fruits.and for the same reason. And their have been people who taught me this. So I think the purpose of the HISPID field is not phenological state, but to alert people about the presence of certain structures, as can also be seen from some of the terms in the vocabulary of the term: 'female flowers' and 'male flowers' are not different phenological states, but they are different structures.

**Comment by nielsklazenga** [comment]
See https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/76.

**Comment by afuchs1** [comment]
Following up from review meeting I have talked to our Cryptogram expert and the vocabulary of 

Gametophyte
Sporophyte
Spore-bearing bodies

covers the requirements. We have some additional terms but they can be mapped to the above.

**Comment by nielsklazenga** [comment]
Please see my note from 17 January.

**Comment by nielsklazenga** [comment]
Actually, 'male flowers' and 'female flowers' are phenological states, as, even in monoecious taxa, they may appear at different times of the year.

**Comment by nielsklazenga** [comment]
Hobart, 2015-10-20:
Comment: "Vocabulary can be extended when new terms are suggested, especially for cryptogams."

**Comment by AaronWilton** [comment]
xml updated to validate and reference HISPID 3 in the terms
