### ISSUE TITLE
maximumElevationInMeters

### ISSUE THREAD

**Issue by acvaughan** [hiscom/hispid#130]
At MEL we use maximumElevationInMeters for either the higher elevation in a range, or the elevation if it's given as, e.g. <200 m. Is it worth spelling this out in the Usage notes? I remember a longish discussion on the TDWG list a few years ago about how maximumElevation should be used, so I tend to think more information is better than less.

**Comment by nielsklazenga** [comment]
Technically speaking, in Darwin Core, if there is a given altitude, you always give both minimumElevationInMeters and maximumElevationInMeters. They are the same if a single altitude value is given. In the '<200 m' example, it is minimumElevationInMeters, not maximumElevationInMeters, that is problematic, as that would have to be '0' (?). That's why there is verbatimElevation as well.

The discussion on the TDWG list was about another use case, namely using minimumElevationInMeters and maximumElevationInMeters to indicate uncertainty (a verbatimElevation of '200±10 m' would become minimumElevationInMeters '190' and maximumElevationInMeters '210'), or the other way around.

**Comment by acvaughan** [comment]
There have been two discussions on the TDWG list about Elevation, but, having checked, I didn't recall their content very accurately; one was about how it relates to distanceAboveSurface and Depth (i.e. whether Elevation values should be the inverse of the depth values, and whether distanceAboveSurface should be combined with Elevation). But I don't think we need to get into that. 

I think if we're using both minimumElevationInMetres and maximumElevationInMetres, the minimumElevationInMetres for the <200 m example should be the lowest point in the area defined by the Location/locality, not "0". i.e. It doesn't make sense to put "0" in minimumElevationInMetres if you're given an elevation of <800 m and the locality (?Location) is the Atherton Tableland. 
But who's going to bother figuring that out? Pretty much no-one. So, failing that, I think "0" is better than "800" in minimumElevationInMetres in this case; it gives you an indication of the uncertainty before you look in verbatimElevation.
(Sorry that this isn't very clearly expressed - I'm still waking up.)

**Comment by nielsklazenga** [comment]
Yes, you are right. I remember that other discussion now as well.

On consideration, I think a minimumElevationInMeters of NULL (a.k.a. not filling it in) is the best thing to do in the < 200 m case. So what we've always been doing.

Just wanted to indicate that there are two more use cases for minimumElevationInMeters and maximumElevationInMeters in addition to the ones you gave: (1) as the lower and upper limits of a confidence interval and (2) as the single value that is given. VerbatimElevation can be used to indicate which situation we are dealing with.

**Comment by AaronWilton** [comment]
updated rdf with following text:

<skos:note xml:lang="en">This field may be used with minimumElevationInMeters to define an elevation range.  maximumElevationInMeters may be used independently  (i.e. without providing a minimumElevationInMeters)  to provide an upper elevation limit (e.g., <500m)</skos:note>

please re-open issue if revision needed.
