### ISSUE TITLE
New term:  typeStatus

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#50]
Definition:  Code indicating the type status of the collection object.
Comment:  typeStatus has been placed in the HISPID namespace, even though it is available in Darwin Core, because our use is different. In contrast to Darwin Core, in HISPID typeStatus and typifiedName have been separated. Having typeStatus in the HISPID namespace allows us to transfer the type status including or excluding the typified name depending on what circumstances require.

**Comment by AaronWilton** [comment]
i propose the use of a different name for this property to differentiate from the DWC field (even though in a different name space may be confusing?)

nomenclaturalTypeStatus

**Comment by nielsklazenga** [comment]
Let's not. Keeping the term in the HISPID namespace, because our use is slightly different from Darwin Core is already being holier than the pope. Giving it a different property name is overshooting the mark. If you want to differentiate our use from the Darwin Core one, it is the 'status' bit that needs to be done something about. Adding the adjective 'nomenclatural' to do the differentiation is misleading, as the HISPID type status is not more nomenclatural than the Darwin Core one. If anything, I would just put the term back in the Darwin Core namespace.

**Comment by nielsklazenga** [comment]
I have been thinking a bit more about this and now think we shouldn't mint a HISPID term at all and just use [`dwc:typeStatus`](http://rs.tdwg.org/dwc/terms/typeStatus).

In Darwin Core whether you use just the type status name or also include the typified name depends on in what context you use `typeStatus`. If you use it in the [Identification History](http://rs.gbif.org/extension/dwc/identification.xml) extension, you would just use the type status name. When using `typeStatus` in the [Occurrence](http://rs.gbif.org/core/dwc_occurrence.xml) core, I would include the typified name, but not everybody does. Since we already have (hispid:typifiedName)[http://hiscom.chah.org.au/hispid/terms/typeStatus], we would also just include the type status name when using `typeStatus` in the Occurrence core.

**Comment by nielsklazenga** [comment]
The TDWG Ontology has terms for both the use of `typeStatus` as just the type of type, http://rs.tdwg.org/ontology/voc/Specimen#typeStatus, and for `typifiedName`, http://rs.tdwg.org/ontology/voc/Specimen#typeForName. I propose to use those instead of minting our own.

The TDWG Ontology `typeStatus` term comes with a vocabulary: http://rs.tdwg.org/ontology/voc/TaxonName#NomenclaturalTypeTypeTerm.

**Comment by ben3000** [comment]
I'm in favour of reusing Darwin Core rather than implementing our own term, so long as the Darwin Core suits us.

**Comment by AaronWilton** [comment]
i agree Ben

**Comment by nielsklazenga** [comment]
So do I, but it it is a motherhood statement that has nothing in it to disagree with and has no bearing on the question at hand. It is the approach we have taken for every term. What we need to agree on here is whether the Darwin Core usage of the term works for us or not. [Darwin Core usage](http://tdwg.github.io/dwc/terms/index.htm#typeStatus), in the Occurrence core at least, is 'Holotype of Dicranum robustum Hook.f. and Wilson' (for example). If you want to split it up in type of type ('Holotype') and typified name ('Dicranum robustum Hook.f. and Wilson), you'll need other terms. I am perfectly happy with just the Darwin Core term. The HISPID term was added because other people wanted something different.

While in theory you can provide the type designation information in the Identification History extension, you cannot do that for data delivery to AVH (well, you could provide it that way, but it won't end up where you want it to).

**Comment by AaronWilton** [comment]
I personally do not like the fuzzy/multiple use of a single term.   I like/see utility in the wider definition of the DWC term, but would like the more exact fields to be available (e.g., I think typeStatus against a strict vocabulary very useful for faceting)

**Comment by ben3000** [comment]
+1 Aaron.

**Comment by nielsklazenga** [comment]
+2

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Approved (dwc:typeStatus, twdgvoc:typeStatus, typifiedName)

**Comment by AaronWilton** [comment]
Add examples, especially for the format for dwc:typeStatus

**Comment by nielsklazenga** [comment]
Hi Aaron,
I am staying out of the RDF files while you are cleaning up. Here are some examples from AVH:

"HOLOTYPE of Boronia deanei subsp. acutifolia Duretto" [MEL 1058128A]

"ISOTYPE of Agapetes obtusata Sleumer" [CANB 10791.1]

"NEOTYPE of Delphyodon oliganthus K. Schum." [CANB 128144.1]

"SYNTYPE of Leucopogon hookeri Sond." [HO 3691]

"ISOTYPE of Babingtonia bidwillii A.R.Bean, fid. Walsh, N.G., 1999-10-05" [MEL 0272819A]

ABCD (or the GPI standard for that matter) doesn't allow for citation of protologues, so I don't have any of those.

**Comment by AaronWilton** [comment]
hmmm, given the following set of possible examples
```xml
		<skos:example>holotype</skos:example>
		<skos:example>http://hiscom.chah.org.au/hispid/vocabulary/type_status/holotype</skos:example>
		<skos:example>HOLOTYPE of Boronia deanei subsp. acutifolia Duretto</skos:example>
		<skos:example>ISOTYPE of Babingtonia bidwillii A.R.Bean, fid. Walsh, N.G., 1999-10-05</skos:example>
```
also given

> typeStatus has been placed in the HISPID namespace, even though it is available in Darwin Core, because our use is different. In contrast to Darwin Core, in HISPID typeStatus and typifiedName have been separated. Having typeStatus in the HISPID namespace allows us to transfer the type status including or excluding the typified name depending on what circumstances require.

My question is:  why do we have typeStatus in the HISPID name space that can either be only the status as per the vocabulary or include the typified name, when we could use the DWC namespace/concept for the latter?    or is that too simplistic.  I really struggle when I see the examples and the discussion above. 

(a secondary question is when we use vocabs are we intending this to be a full URI or a unqualified text comparing example 1 and 2?) 

PS - i know this is a can of worms, too much time between the discussions and getting this finalised

**Comment by nielsklazenga** [comment]
The first two examples are incorrect. They are not type status, but type of type.

**Comment by AaronWilton** [comment]
ahh yes! now the action note makes sense - we agreed to add the tdwgvoc field (as well as a typfiedName field, but retain dwc:typeStatus).    

WRT the  tdwgvoc field that whole vocabulary has been deprecated without replacement...  in which case I think we mint our own and move on...

**Comment by AaronWilton** [comment]
done - please review and re-open if necessary.
