### ISSUE TITLE
Tissue samples

### ISSUE THREAD

**Issue by acvaughan** [hiscom/hispid#64]
Michelle asks that tissue samples get addressed. A 'tissue sampling for DNA' draft policy has gone from CHAH to MAHC, and when that's signed off, it will need an associated data delivery mechanism. Michelle has discussed this with Niels, so it might already be in here as an issue, but I couldn't see it.

**Comment by nielsklazenga** [comment]
It is sort of addressed in issue #26. No special provisions are needed for dealing with tissue samples in HISPID. A tissue sample is just another preparation type (or kind of unit; we have added 'Silica gel sample', we could add more), so it can either be delivered as just that in an AVH record (which is what we do), or in a separate data set (related resource) using the Darwin Core MaterialSample class instead of the Occurrence class, which we use for AVH.

**Comment by acvaughan** [comment]
Great, thanks Niels.
