### ISSUE TITLE
Artist field

### ISSUE THREAD

**Issue by acvaughan** [hiscom/hispid#65]
We will be delivering images of artworks of specimens, and will need to deliver both photographer and artist.

**Comment by nielsklazenga** [comment]
The record is for the digital resource, not the physical object (artwork), so dcterms:creator is the photographer. The artist can be in dcterms:description and ac:caption and/or there can be a reference to the artwork that was the source of the image via dc:source or dcterms:source.

The Dublin Core definition of dc:creator is 'An entity primarily responsible for making the resource'. Audubon Core doesn't add anything to that. In most cases I would have no problem with giving the artist as the creator as well, but I would prefer to have the photographer or the institution where the photograph was taken as the creator and have the artist in the reference to the source object. Just adding an 'artist' field is apparently very confusing to the punters. We have it in our enterprise image database and it has led to never-ending discussions as to what goes into which field and quite a mess in the database.

**Comment by AaronWilton** [comment]
I agree

**Comment by afuchs1** [comment]
Also agree Niels.

**Comment by ben3000** [comment]
Yep, I agree too.

**Comment by nielsklazenga** [comment]
There is actually a `creator {Artwork or Object detail}` element in the new IPTC metadata standard (version 1.2; http://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata), which we can use for this. The XMP implementation is `Iptc4XmpExt:AOCreator`. The `Iptc4XmpExt` namespace is already used in Audubon Core.

In the new edition of the IPTC metadata standard extra properties have been added to the 'Artwork or Object in the Image structure' (I've got this from the [summary](https://iptc.org/standards/photo-metadata/iptc-standard/); I don't know it because I know the different versions of IPTC so well), so apart from the creator, it also allows for rights data, more detailed descriptions, approximate dates of creation, style period, etc. (for the artwork).

The _Artwork or Object in the Image_ extension resolves the initial issue I had with not being able to distinguish between the digital resource and the physical object that is the source. I don't think we need to add `AOCreator` to HISPID, but if there is a need to deliver the information, this is the element we should use.
